/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Routes */
        get: operations["routes_api_routes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instruments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Instruments */
        get: operations["instruments_api_instruments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/objectives/compile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compile Endpoint */
        post: operations["compile_endpoint_api_objectives_compile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Run */
        post: operations["create_run_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Events */
        get: operations["get_events_api_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Run */
        post: operations["cancel_run_api_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlphaFoldModel */
        AlphaFoldModel: {
            /** Entry Id */
            entry_id: string;
            /** Uniprot Accession */
            uniprot_accession: string;
            /** Uniprot Id */
            uniprot_id?: string | null;
            /** Uniprot Description */
            uniprot_description?: string | null;
            /** Organism Scientific Name */
            organism_scientific_name?: string | null;
            /** Tax Id */
            tax_id?: number | null;
            /** Sequence */
            sequence?: string | null;
            /** Global Metric Value */
            global_metric_value?: number | null;
            /** Fraction Plddt Very Low */
            fraction_plddt_very_low?: number | null;
            /** Fraction Plddt Low */
            fraction_plddt_low?: number | null;
            /** Fraction Plddt Confident */
            fraction_plddt_confident?: number | null;
            /** Fraction Plddt Very High */
            fraction_plddt_very_high?: number | null;
            /** Latest Version */
            latest_version?: number | null;
            /** Model Created Date */
            model_created_date?: string | null;
            /** Cif Url */
            cif_url?: string | null;
            /** Pdb Url */
            pdb_url?: string | null;
            /** Bcif Url */
            bcif_url?: string | null;
        };
        /**
         * ArchitectureKind
         * @enum {string}
         */
        ArchitectureKind: "single_scaffold" | "fusion_reporter" | "co_encapsulated_pair" | "surface_immobilized" | "electrode_coupled" | "material_composite";
        /** BindingSite */
        BindingSite: {
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Ligand Name */
            ligand_name?: string | null;
            /** Ligand Id */
            ligand_id?: string | null;
        };
        /** CandidateDossier */
        CandidateDossier: {
            /** Dossier Id */
            dossier_id: string;
            candidate: components["schemas"]["CandidateRecord"];
            physics_eligibility: components["schemas"]["PhysicsEligibility"];
            structural_evidence: components["schemas"]["StructuralEvidence"];
            /** Evidence Citations */
            evidence_citations?: components["schemas"]["Citation"][];
            /** @default diagnostic_only */
            claim_ceiling: components["schemas"]["ClaimLevel"];
            /** Disclaimers */
            disclaimers?: string[];
            /**
             * Status
             * @default public_hypothesis_not_validated
             * @constant
             */
            status: "public_hypothesis_not_validated";
            /**
             * Private Candidate
             * @default false
             * @constant
             */
            private_candidate: false;
        };
        /** CandidateRecord */
        CandidateRecord: {
            /** Candidate Id */
            candidate_id: string;
            /** Title */
            title: string;
            /**
             * Status
             * @default public_hypothesis_not_validated
             * @constant
             */
            status: "public_hypothesis_not_validated";
            /**
             * Private Candidate
             * @default false
             * @constant
             */
            private_candidate: false;
            scaffold_family: components["schemas"]["ScaffoldFamily"];
            architecture_kind: components["schemas"]["ArchitectureKind"];
            uniprot?: components["schemas"]["UniProtRecord"] | null;
            /** Interpro Matches */
            interpro_matches?: components["schemas"]["InterProMatch"][];
            /** Pdb Entries */
            pdb_entries?: components["schemas"]["PdbEntry"][];
            alphafold_model?: components["schemas"]["AlphaFoldModel"] | null;
            fpbase?: components["schemas"]["FpbaseProtein"] | null;
            /** Cofactors */
            cofactors?: components["schemas"]["CofactorRef"][];
            /** Readout Modes */
            readout_modes?: components["schemas"]["ReadoutMode"][];
            /** Mechanism Route Id */
            mechanism_route_id: string;
            route_class: components["schemas"]["RouteClass"];
            /** Why It Might Work */
            why_it_might_work?: string[];
            /** Why It Might Fail */
            why_it_might_fail?: string[];
            /** Required Controls */
            required_controls?: string[];
            /** Confounders */
            confounders?: string[];
            /** Evidence Card Ids */
            evidence_card_ids?: string[];
            /** Analogs */
            analogs?: components["schemas"]["PublicAnalog"][];
            /** Material Fit */
            material_fit?: string[];
            /** Expression Context */
            expression_context?: string[];
            /** @default diagnostic_only */
            claim_ceiling: components["schemas"]["ClaimLevel"];
            /**
             * Generated By
             * @description e.g. 'generated from UniProt Q43125 via cryptochrome_FAD_radical_pair'
             */
            generated_by: string;
            /**
             * Allowed Next Step
             * @default measurement_planning
             * @enum {string}
             */
            allowed_next_step: "measurement_planning" | "internal_developability_triage" | "discard";
            /** Provenance */
            provenance?: components["schemas"]["Provenance"][];
            /**
             * Degradations
             * @description explicit unavailable/degraded states — never imputed
             */
            degradations?: string[];
        };
        /** Citation */
        Citation: {
            /** Authors */
            authors: string;
            /** Year */
            year: number;
            /** Title */
            title: string;
            /** Venue */
            venue: string;
            /** Doi */
            doi: string;
        };
        /**
         * ClaimLevel
         * @enum {string}
         */
        ClaimLevel: "diagnostic_only" | "measurement_triage" | "partner_ready_dossier";
        /** CofactorRef */
        CofactorRef: {
            /** Name */
            name: string;
            /** Chebi Id */
            chebi_id?: string | null;
            /** Note */
            note?: string | null;
        };
        /** CompileRequest */
        CompileRequest: {
            /** Objective Text */
            objective_text: string;
            /**
             * User Mode
             * @default novice
             */
            user_mode: string;
            /** Instrument Id */
            instrument_id?: string | null;
            /**
             * Seed
             * @default 1337
             */
            seed: number;
        };
        /**
         * ExpressionHost
         * @enum {string}
         */
        ExpressionHost: "bacteria" | "yeast" | "mammalian" | "cell_free" | "unknown";
        /**
         * FieldProvenance
         * @description How each compiled field was obtained — honesty scales beyond a flat list.
         */
        FieldProvenance: {
            /** Field */
            field: string;
            /**
             * Source
             * @enum {string}
             */
            source: "verbatim" | "inferred" | "defaulted";
            /**
             * By
             * @enum {string}
             */
            by: "llm" | "rule";
            /** Note */
            note?: string | null;
        };
        /** FpbaseProtein */
        FpbaseProtein: {
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Uuid */
            uuid?: string | null;
            /** Seq */
            seq?: string | null;
            /** Agg */
            agg?: string | null;
            /** Switch Type */
            switch_type?: string | null;
            /** Uniprot */
            uniprot?: string | null;
            /** Pdb */
            pdb?: string[];
            /** Doi */
            doi?: string | null;
            /** States */
            states?: components["schemas"]["FpbaseState"][];
        };
        /** FpbaseState */
        FpbaseState: {
            /** Name */
            name?: string | null;
            /** Ex Max */
            ex_max?: number | null;
            /** Em Max */
            em_max?: number | null;
            /** Qy */
            qy?: number | null;
            /** Ext Coeff */
            ext_coeff?: number | null;
            /** Brightness */
            brightness?: number | null;
            /** Pka */
            pka?: number | null;
            /** Lifetime */
            lifetime?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Status */
            status: string;
            /** Offline */
            offline: boolean;
            /** Providers */
            providers: {
                [key: string]: boolean;
            };
            /** Version */
            version: string;
        };
        /** InterProFragment */
        InterProFragment: {
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Dc Status */
            dc_status?: string | null;
        };
        /** InterProLocation */
        InterProLocation: {
            /** Fragments */
            fragments?: components["schemas"]["InterProFragment"][];
            /** Representative */
            representative?: boolean | null;
            /** Score */
            score?: number | null;
        };
        /** InterProMatch */
        InterProMatch: {
            /** Interpro Accession */
            interpro_accession: string;
            /** Name */
            name?: string | null;
            /** Entry Type */
            entry_type?: string | null;
            /** Source Database */
            source_database?: string | null;
            /** Go Terms */
            go_terms?: string[];
            /** Locations */
            locations?: components["schemas"]["InterProLocation"][];
        };
        /** Keyword */
        Keyword: {
            /** Id */
            id: string;
            /** Category */
            category?: string | null;
            /** Name */
            name: string;
        };
        /**
         * MaterialContext
         * @enum {string}
         */
        MaterialContext: "hydrogel" | "film" | "chip" | "cell" | "solution" | "wearable" | "unknown";
        /**
         * ObjectiveSpec
         * @description Structured, editable objective. Superset of the TS `ObjectiveInput`.
         */
        ObjectiveSpec: {
            /**
             * Schema Version
             * @default 2.0.0
             */
            schema_version: string;
            /** Objective Id */
            objective_id: string;
            /** Objective Text */
            objective_text: string;
            /**
             * User Mode
             * @default novice
             * @enum {string}
             */
            user_mode: "novice" | "expert";
            /** Application Domain */
            application_domain?: string | null;
            /** Intended Function */
            intended_function?: string | null;
            /** Sensed Quantity Or State */
            sensed_quantity_or_state?: string | null;
            /** Desired Modalities */
            desired_modalities?: components["schemas"]["ReadoutMode"][];
            /** Acceptable Readouts */
            acceptable_readouts?: components["schemas"]["ReadoutMode"][];
            /** @default unknown */
            material_context: components["schemas"]["MaterialContext"];
            /** Immobilization Or Integration */
            immobilization_or_integration?: string | null;
            /** @default unknown */
            expression_host: components["schemas"]["ExpressionHost"];
            /** Allowed Cofactors */
            allowed_cofactors?: string[];
            /** Excluded Cofactors */
            excluded_cofactors?: string[];
            /**
             * Excitation Allowed
             * @description excitation labels, e.g. blue-light/green-light/red-light/UV
             */
            excitation_allowed?: string[];
            /** Excitation Ranges Nm */
            excitation_ranges_nm?: [
                number,
                number
            ][];
            /** Static Field Range Mt */
            static_field_range_mT?: [
                number,
                number
            ] | null;
            /** Rf Frequency Range Mhz */
            rf_frequency_range_MHz?: [
                number,
                number
            ] | null;
            /** Temperature Range C */
            temperature_range_C?: [
                number,
                number
            ] | null;
            /** Ph Range */
            pH_range?: [
                number,
                number
            ] | null;
            /**
             * Oxygen Condition
             * @default unknown
             * @enum {string}
             */
            oxygen_condition: "aerobic" | "anaerobic" | "controlled" | "unknown";
            /**
             * Response Direction
             * @default unknown
             * @enum {string}
             */
            response_direction: "increase" | "decrease" | "either" | "unknown";
            /**
             * Minimum Effect Size
             * @description required |ΔF/F| or dynamic range
             */
            minimum_effect_size?: number | null;
            /** Maximum Response Time S */
            maximum_response_time_s?: number | null;
            /** Assay Geometry */
            assay_geometry?: string | null;
            /** Available Instrumentation */
            available_instrumentation?: string[];
            /** Instrument Id */
            instrument_id?: string | null;
            /**
             * Optimization Objectives
             * @description (component_name, weight) pairs
             */
            optimization_objectives?: [
                string,
                number
            ][];
            /** Hard Constraints */
            hard_constraints?: string[];
            /** Soft Preferences */
            soft_preferences?: string[];
            /**
             * Seed Query
             * @description explicit UniProt Lucene query for expert mode
             */
            seed_query?: string | null;
            /** Seed Accessions */
            seed_accessions?: string[];
            /** Target Scaffold Families */
            target_scaffold_families?: components["schemas"]["ScaffoldFamily"][];
            /**
             * Include Unreviewed
             * @default false
             */
            include_unreviewed: boolean;
            /** Manufacturing Constraints */
            manufacturing_constraints?: string[];
            /** Safety Constraints */
            safety_constraints?: string[];
            /** Constraints */
            constraints?: string[];
            /** Unknowns */
            unknowns?: string[];
            /** Assumptions */
            assumptions?: string[];
            /** Missing Information */
            missing_information?: string[];
            /** Forbidden Assumptions */
            forbidden_assumptions?: string[];
            /** Field Provenance */
            field_provenance?: components["schemas"]["FieldProvenance"][];
            /**
             * Confidential Sequence Provided
             * @default false
             * @constant
             */
            confidential_sequence_provided: false;
            /**
             * Seed
             * @default 1337
             */
            seed: number;
        };
        /**
         * ParameterProvenance
         * @description Full provenance for one numeric (or database-descriptor) parameter.
         */
        ParameterProvenance: {
            /** Name */
            name: string;
            /** Value */
            value: number | string;
            /** Unit */
            unit: string;
            /** Range */
            range: [
                number,
                number
            ];
            uncertainty: components["schemas"]["Uncertainty"];
            source_type: components["schemas"]["ParameterSourceType"];
            /** Citation Or Assumption */
            citation_or_assumption: string;
            /** Applicability Limits */
            applicability_limits: string;
        };
        /**
         * ParameterSourceType
         * @enum {string}
         */
        ParameterSourceType: "database" | "literature" | "assumption" | "instrument" | "user_constraint" | "computed";
        /** PdbCofactor */
        PdbCofactor: {
            /** Comp Id */
            comp_id: string;
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Formula */
            formula?: string | null;
            /** Formula Weight Da */
            formula_weight_da?: number | null;
            /** Auth Asym Ids */
            auth_asym_ids?: string[];
        };
        /** PdbEntry */
        PdbEntry: {
            /** Rcsb Id */
            rcsb_id: string;
            /** Title */
            title?: string | null;
            /** Experimental Method */
            experimental_method?: string | null;
            /** Resolution Combined */
            resolution_combined?: number[];
            /** Nonpolymer Bound Components */
            nonpolymer_bound_components?: string[];
            /** Polymer Entity Count */
            polymer_entity_count?: number | null;
            /** Nonpolymer Entity Count */
            nonpolymer_entity_count?: number | null;
            /** Cofactors */
            cofactors?: components["schemas"]["PdbCofactor"][];
            /** Coordinates Url */
            coordinates_url?: string | null;
        };
        /** PdbXref */
        PdbXref: {
            /** Id */
            id: string;
            /** Method */
            method?: string | null;
            /** Resolution */
            resolution?: string | null;
            /** Chains */
            chains?: string | null;
        };
        /** PhysicsEligibility */
        PhysicsEligibility: {
            /** Candidate Id */
            candidate_id: string;
            route_class: components["schemas"]["RouteClass"];
            kind: components["schemas"]["PhysicsEligibilityKind"];
            /** Has Required Cofactor */
            has_required_cofactor: boolean;
            /** Cofactor Id */
            cofactor_id?: string | null;
            spin_dynamics_plan?: components["schemas"]["SpinDynamicsPlan"] | null;
            qm_cluster_plan?: components["schemas"]["QmClusterPlan"] | null;
            /**
             * Offline Budget Seconds
             * @default 0
             */
            offline_budget_seconds: number;
            /** Reason */
            reason: string;
            /**
             * Label
             * @default assumption_derived_not_whole_protein_spin_response
             * @constant
             */
            label: "assumption_derived_not_whole_protein_spin_response";
            /** Assumptions */
            assumptions?: components["schemas"]["ParameterProvenance"][];
        };
        /**
         * PhysicsEligibilityKind
         * @enum {string}
         */
        PhysicsEligibilityKind: "real_spin_dynamics" | "qm_cluster_assumption" | "analytic_proxy_only" | "ineligible";
        /**
         * Provenance
         * @description Retrieval-time provenance for one provider call.
         */
        Provenance: {
            provider: components["schemas"]["ProviderId"];
            /**
             * Endpoint Url
             * @description the exact URL fetched (or the fixture path)
             */
            endpoint_url: string;
            /** Http Status */
            http_status?: number | null;
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
            mode: components["schemas"]["RetrievalMode"];
            /**
             * Source Release
             * @description e.g. UniProt x-uniprot-release '2026_02'; None where the provider exposes no version
             */
            source_release?: string | null;
            /** Cache Control */
            cache_control?: string | null;
            /** Etag */
            etag?: string | null;
            /** License Note */
            license_note?: string | null;
            citation?: components["schemas"]["Citation"] | null;
            /**
             * Disclaimer
             * @default public reference retrieval, not sensor validation
             */
            disclaimer: string;
        };
        /**
         * ProviderId
         * @enum {string}
         */
        ProviderId: "uniprot" | "interpro" | "rcsb" | "alphafold" | "fpbase";
        /**
         * PublicAnalog
         * @description Retrieval-only public analog — analog != prediction (never spin response).
         */
        PublicAnalog: {
            /** Accession Or Id */
            accession_or_id: string;
            /** Name */
            name: string;
            /** Family */
            family?: string | null;
            /**
             * Method
             * @default keyword
             * @enum {string}
             */
            method: "mmseqs2" | "esm2_embedding" | "keyword";
            /** Similarity */
            similarity: number;
            /** Public Ref */
            public_ref: string;
        };
        /**
         * QmClusterPlan
         * @description A PySCF open-shell single-point plan on a truncated public cofactor cluster.
         *
         *     Budget envelope is MEASURED, not guessed (recon): ~14 heavy atoms = 30 s at
         *     6-31G*, 8 s at 6-31G, 1.6 s at sto-3g. Full flavin is intractable → truncate.
         */
        QmClusterPlan: {
            /**
             * Core
             * @default isoalloxazine
             */
            core: string;
            /** Heavy Atom Estimate */
            heavy_atom_estimate: number;
            /**
             * Basis
             * @default 6-31G
             * @enum {string}
             */
            basis: "sto-3g" | "6-31G" | "6-31G*";
            /**
             * Method
             * @default UHF
             * @enum {string}
             */
            method: "UHF" | "ROHF";
            /**
             * Spin
             * @default 1
             */
            spin: number;
            /**
             * Charge
             * @default 0
             */
            charge: number;
            /** Est Wall Seconds */
            est_wall_seconds: number;
            /** Tractable Under 60S */
            tractable_under_60s: boolean;
            /**
             * Truncation Note
             * @default ribityl/phosphate tail truncated to an N10-methyl cap; dangling bonds H-capped (standard QM-cluster truncation). Assumption-derived; not a whole-protein claim.
             */
            truncation_note: string;
        };
        /**
         * ReadoutMode
         * @enum {string}
         */
        ReadoutMode: "fluorescence" | "lifetime" | "RF_magnetic" | "ODMR_like" | "redox_electrochemical" | "material_state";
        /**
         * RetrievalMode
         * @enum {string}
         */
        RetrievalMode: "live" | "cached" | "fixture" | "unavailable";
        /**
         * RouteClass
         * @enum {string}
         */
        RouteClass: "LOV_flavin_radical_pair" | "cryptochrome_FAD_radical_pair" | "triplet_FP" | "RFP_flavin_photochemical" | "redox_electrochemical" | "material_state" | "metal_cofactor_confounder" | "unsupported";
        /**
         * RunCreated
         * @description Response to POST /api/runs.
         */
        RunCreated: {
            /** Run Id */
            run_id: string;
            status: components["schemas"]["RunStatus"];
            /** Input Fingerprint */
            input_fingerprint: string;
        };
        /** RunEvent */
        RunEvent: {
            /**
             * At
             * Format: date-time
             */
            at: string;
            from_status?: components["schemas"]["RunStatus"] | null;
            to_status: components["schemas"]["RunStatus"];
            /** Stage */
            stage: string;
            /** Note */
            note?: string | null;
            /** Progress */
            progress?: number | null;
        };
        /** RunState */
        RunState: {
            /** Run Id */
            run_id: string;
            /** Input Fingerprint */
            input_fingerprint: string;
            /** @default queued */
            status: components["schemas"]["RunStatus"];
            /**
             * Seed
             * @default 1337
             */
            seed: number;
            objective: components["schemas"]["ObjectiveSpec"];
            /** Instrument Id */
            instrument_id?: string | null;
            /**
             * Current Stage
             * @default queued
             */
            current_stage: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Candidates */
            candidates?: components["schemas"]["CandidateRecord"][];
            /** Dossiers */
            dossiers?: components["schemas"]["CandidateDossier"][];
            /** Selected Candidate Id */
            selected_candidate_id?: string | null;
            /** Result Ref */
            result_ref?: string | null;
            /** Provider Calls */
            provider_calls?: components["schemas"]["Provenance"][];
            /** Events */
            events?: components["schemas"]["RunEvent"][];
            /** Errors */
            errors?: string[];
            /**
             * Offline
             * @default true
             */
            offline: boolean;
            /**
             * Status Note
             * @default diagnostic_only_not_validated
             * @constant
             */
            status_note: "diagnostic_only_not_validated";
        };
        /**
         * RunStatus
         * @enum {string}
         */
        RunStatus: "queued" | "compiling_objective" | "retrieving_evidence" | "assessing_physics" | "simulating" | "ranking" | "planning" | "completed" | "failed" | "cancelled";
        /**
         * ScaffoldFamily
         * @enum {string}
         */
        ScaffoldFamily: "LOV_flavin" | "cryptochrome_FAD" | "fluorescent_protein" | "RFP_plus_flavin" | "metal_cofactor" | "redox_flavoprotein" | "material_composite" | "unsupported";
        /**
         * SpinDynamicsPlan
         * @description References the offline RadicalPy artifact; no per-protein spin claim.
         */
        SpinDynamicsPlan: {
            /** Artifact Ref */
            artifact_ref: string;
            /** Hamiltonian Terms */
            hamiltonian_terms?: string[];
            /**
             * Note
             * @default spin dynamics of a model flavin-based radical pair; a calibration reference, not a candidate-specific prediction
             */
            note: string;
        };
        /** StructuralEvidence */
        StructuralEvidence: {
            /** Pdb Entries */
            pdb_entries?: components["schemas"]["PdbEntry"][];
            alphafold_model?: components["schemas"]["AlphaFoldModel"] | null;
            /**
             * Note
             * @default PDB = experimental; AlphaFold = computational prediction (pLDDT confidence)
             */
            note: string;
        };
        /**
         * Uncertainty
         * @enum {string}
         */
        Uncertainty: "low" | "medium" | "high";
        /** UniProtRecord */
        UniProtRecord: {
            /** Primary Accession */
            primary_accession: string;
            /** Uniprotkb Id */
            uniprotkb_id?: string | null;
            /** Entry Type */
            entry_type?: string | null;
            /**
             * Reviewed
             * @default false
             */
            reviewed: boolean;
            /** Protein Name */
            protein_name?: string | null;
            /** Organism Scientific Name */
            organism_scientific_name?: string | null;
            /** Organism Common Name */
            organism_common_name?: string | null;
            /** Organism Tax Id */
            organism_tax_id?: number | null;
            /** Sequence */
            sequence?: string | null;
            /** Sequence Length */
            sequence_length?: number | null;
            /** Mol Weight Da */
            mol_weight_da?: number | null;
            /** Functions */
            functions?: string[];
            /** Cofactors */
            cofactors?: components["schemas"]["CofactorRef"][];
            /** Subcellular Locations */
            subcellular_locations?: string[];
            /** Keywords */
            keywords?: components["schemas"]["Keyword"][];
            /** Binding Sites */
            binding_sites?: components["schemas"]["BindingSite"][];
            /** Pdb Xrefs */
            pdb_xrefs?: components["schemas"]["PdbXref"][];
            /** Alphafold Id */
            alphafold_id?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    routes_api_routes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    instruments_api_instruments_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    compile_endpoint_api_objectives_compile_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompileRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObjectiveSpec"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_api_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_events_api_runs__run_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunEvent"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_api_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
